CREATE TABLE IF NOT EXISTS whatsapp_pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  telefono VARCHAR(30) NOT NULL,
  nombre_cliente VARCHAR(100) NULL,
  items JSON NOT NULL,
  total DECIMAL(10,2) NOT NULL DEFAULT 0,
  notas TEXT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
